### ISSUE TITLE
Arrumar os algoritmos por pasta

### ISSUE THREAD

**Issue by gitarno** [ninjadabike/Iniciando_programacao#4]
Organize seus projeto por pastas... facilita o entendimento do que realmente esta produzindo.. 

Minha sugestão inicial

```
|- root_folder 
|-+ src 
|-+ docs
|-+ readme.md 
...  
```

_SRC_ - Códigos originais essa pasta contem todos os códigos criados e manipulados 
_DOCS_ - Documentos específicos do projeto... docs, xls, imagens... nada que vai ir diretamente no projeto final...

_README.md_ - Arquivo Markdown para descrever sua pasta , esse arquivo pode estar em cada pasta que deseja descrever algo.

**Comment by ninjadabike** [comment]
fis os ajustes acredito que seja isso veja se está certo. Obrigado.
